In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot  as plt
import seaborn as sns

In [3]:
np.__version__

'1.21.5'

In [61]:
df = pd.read_csv("data.csv")
len(df)

11914

In [62]:
df.groupby("Make").count().sort_values(by='Model')

,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
Make,,,,,,,,,,,,,,,
Genesis,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
Spyker,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
Bugatti,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
Alfa Romeo,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
McLaren,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
Maybach,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16
HUMMER,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17
Tesla,18,18,18,0,18,18,18,13,18,18,18,18,18,18,18
Lotus,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29
Rolls-Royce,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31
Lamborghini,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52
Maserati,58,58,58,58,58,58,58,58,58,58,58,58,58,58,58
Scion,60,60,60,60,60,60,60,60,48,60,60,60,60,60,60
FIAT,62,62,62,59,62,62,62,62,41,62,62,62,62,62,62
Ferrari,69,69,69,69,69,69,69,68,69,69,69,69,69,69,69
Bentley,74,74,74,74,74,74,74,74,74,74,74,74,74,74,74
Plymouth,82,82,82,82,82,82,82,82,39,82,82,82,82,82,82
Aston Martin,93,93,93,93,93,93,93,93,93,93,93,93,93,93,93
Saab,111,111,111,111,111,111,111,111,111,111,111,111,111,111,111
Porsche,136,136,136,136,136,136,136,136,136,136,136,136,136,136,136
Land Rover,143,143,143,143,143,143,143,143,143,143,143,143,143,143,143
Oldsmobile,150,150,150,150,150,150,150,150,3,150,150,150,150,150,150
Lincoln,164,164,164,156,164,164,164,164,164,164,164,164,164,164,164
Pontiac,186,186,186,186,186,186,186,186,77,186,186,186,186,186,186
Chrysler,187,187,187,187,187,187,187,187,108,187,187,187,187,187,187
Buick,196,196,196,196,196,196,196,196,125,196,196,196,196,196,196
Lexus,202,202,202,202,202,202,202,202,202,202,202,202,202,202,202
Mitsubishi,213,213,213,212,210,213,213,213,128,213,213,213,213,213,213
Kia,231,231,231,226,231,231,231,231,109,231,231,231,231,231,231
Acura,252,252,252,252,252,252,252,252,252,252,252,252,252,252,252
Subaru,256,256,256,256,256,256,256,256,214,256,256,256,256,256,256
Volvo,281,281,281,281,281,281,281,281,281,281,281,281,281,281,281
Hyundai,303,303,303,303,303,303,303,303,214,303,303,303,303,303,303
Audi,328,328,328,328,328,328,328,328,328,328,328,328,328,328,328
Infiniti,330,330,330,330,330,330,330,330,330,330,330,330,330,330,330
BMW,334,334,334,334,334,334,334,334,334,334,334,334,334,334,334
Suzuki,351,351,348,351,351,351,351,351,99,351,351,351,351,351,351
Mercedes-Benz,353,353,353,352,353,353,353,353,353,353,353,353,353,353,353
Cadillac,397,397,397,397,397,397,397,397,397,397,397,397,397,397,397
Mazda,423,423,423,423,403,423,423,423,259,423,423,423,423,423,423
Honda,449,449,449,447,449,449,449,449,284,449,449,449,449,449,449
GMC,515,515,515,515,515,515,515,515,270,515,515,515,515,515,515
Nissan,558,558,558,548,558,558,558,558,318,558,558,558,558,558,558
Dodge,626,626,626,626,626,626,626,626,320,626,626,626,626,626,626
Toyota,746,746,746,744,745,746,746,746,303,746,746,746,746,746,746
Volkswagen,809,809,809,809,805,809,809,809,585,809,809,809,809,809,809
Ford,881,881,881,868,881,881,881,881,499,881,881,881,881,881,881
Chevrolet,1123,1123,1123,1117,1121,1123,1123,1123,622,1123,1123,1123,1123,1123,1123

In [63]:
len(df[df["Make"] == "Audi"]["Model"].unique())

34

In [64]:
df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [65]:
df["Engine Cylinders"].median()

6.0

In [66]:
df["Engine Cylinders"] = df["Engine Cylinders"].fillna(value=df["Engine Cylinders"].mode()[0])

In [67]:
df["Engine Cylinders"].median()

6.0

In [78]:
df2 = df[df["Make"] == "Lotus"][["Engine HP","Engine Cylinders"]].drop_duplicates()

In [110]:
x = df2.to_numpy()

In [111]:
XTX = x.T.dot(x)

In [112]:
x_invers = np.linalg.inv(XTX)

In [113]:
x_invers

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [114]:
y = np.array([1100,800,750,850,1300,1000,1000,1300,800])

In [115]:
w = x_invers.dot(x.T) * y
w

array([[-1.45145106e+00,  2.27554657e-01,  1.71851173e-01,
        -3.55949211e+00,  5.80343386e+00, -2.39406462e+00,
         1.42221660e+00,  3.17391339e+00,  1.20098291e+00],
       [ 9.46982487e+01,  5.89254188e-01,  2.75982449e+00,
         2.16399957e+02, -2.77873207e+02,  1.51207962e+02,
        -5.18727169e+01, -1.48262613e+02, -5.12110350e+01]])

In [116]:
w[0].sum()

4.594944810094579